name: ci_as_private
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: bagbyte/use-private-action@v0.0.2
        with:
            private-action: LumaKernel/example-action@master
            private-action-token: ${{ secrets.REPO_TOKEN }}
